export const IPC_CHANNELS = {
  APP: {
    GET_VERSION: "app:get-version",
    GET_DB_LOCATION: "app:get-db-location",
    OPEN_EXTERNAL: "app:open-external",
    DOWNLOAD_FILE: "app:download-file",
    WRITE_CLIPBOARD: "app:write-to-clipboard",
    LOGOUT: "app:logout",
    VERIFY_CREDS: "app:verify-creds",
  },
  SETTINGS: {
    GET: "app:get-settings-status",
    SAVE: "app:save-settings",
    CONFIRM_LEGAL: "settings:confirm-legal",
    SAVE_DOWNLOAD_FOLDER: "settings:save-download-folder",
    SAVE_DOWNLOAD_SETTINGS: "settings:save-download-settings",
  },
  DB: {
    GET_DOWNLOAD_ITEMS: "db:get-download-items",
    GET_ARTISTS: "db:get-artists",
    ADD_ARTIST: "db:add-artist",
    DELETE_ARTIST: "db:delete-artist",
    SEARCH_TAGS: "db:search-tags",
    GET_POSTS: "db:get-posts",
    GET_POSTS_COUNT: "db:get-posts-count",
    GET_POSTS_COUNT_WITH_FILTERS: "db:get-posts-count-with-filters",
    MARK_VIEWED: "db:mark-post-viewed",
    TOGGLE_FAVORITE: "db:toggle-post-favorite",
    SYNC_ALL: "db:sync-all",
    TOGGLE_POST_VIEWED: "db:toggle-post-viewed" as const,
    RESET_POST_CACHE: "db:reset-post-cache" as const,
    SHADOW_INSERT_POST: "db:shadow-insert-post" as const,
    GET_API_KEY_ENCRYPTED: "db:get-api-key-encrypted",
    CREATE_PLAYLIST: "db:create-playlist",
    GET_PLAYLISTS: "db:get-playlists",
    GET_PLAYLIST: "db:get-playlist",
    UPDATE_PLAYLIST: "db:update-playlist",
    DELETE_PLAYLIST: "db:delete-playlist",
    ADD_POSTS_TO_PLAYLIST: "db:add-posts-to-playlist",
    REMOVE_POSTS_FROM_PLAYLIST: "db:remove-posts-from-playlist",
    GET_PLAYLIST_POSTS: "db:get-playlist-posts",
    RESOLVE_PLAYLIST_POSTS: "db:resolve-playlist-posts",
    GET_PLAYLISTS_CONTAINING_POST: "db:get-playlists-containing-post",
    GET_PLAYLIST_DOWNLOAD_ITEMS: "db:get-playlist-download-items",
  },
  API: {
    SEARCH_REMOTE: "api:search-remote-tags",
    SEARCH_POSTS: "booru:search",
    RESOLVE_TAGS: "booru:resolve-tags",
    RESOLVE_CHARACTER_TAGS: "booru:resolve-character-tags",
    RESOLVE_COPYRIGHT_TAGS: "booru:resolve-copyright-tags",
    RESOLVE_TAGS_BY_TYPE: "booru:resolve-tags-by-type",
  },
  BACKUP: {
    CREATE: "db:create-backup",
    RESTORE: "db:restore-backup",
  },
  SYNC: {
    REPAIR: "sync:repair-artist",
  },

  FILES: {
    DOWNLOAD: "files:download",
    DOWNLOAD_ALL: "files:download-all",
    CANCEL_DOWNLOAD_ALL: "files:cancel-download-all",
    PAUSE_DOWNLOAD_ALL: "files:pause-download-all",
    RESUME_DOWNLOAD_ALL: "files:resume-download-all",
    GET_PENDING_DOWNLOAD: "files:get-pending-download",
    RESUME_PENDING_DOWNLOAD: "files:resume-pending-download",
    DISMISS_PENDING_DOWNLOAD: "files:dismiss-pending-download",
    OPEN_FOLDER: "files:open-folder",
    DOWNLOAD_PROGRESS: "files:download-progress",
    DOWNLOAD_ALL_PROGRESS: "files:download-all-progress",
    PENDING_DOWNLOAD_STATE_CHANGED: "files:pending-download-state-changed",
    SELECT_DOWNLOAD_FOLDER: "files:select-download-folder",
  },
} as const;
